### ISSUE TITLE
Migration information seems to be missing. 

### ISSUE THREAD

**Issue by willhaslett** [jama5262/jiffy#101]
The change away from implicit casting to `DateTime`s with 4.0.0 seems like a good one. However, this is an important, breaking change and I don't see any guidance. There's got to be a lot of code out there that broke because it expected the output of a method call on a Jiffy object to return a DateTime. An example:

This worked before
```Dart
DateTime time = startTime = Jiffy(Jiffy(currentTime).add(weeks: timeOffset * 7)).startOf(Units.WEEK);
```

And this works now
```Dart
Jiffy jiffyTime = Jiffy(Jiffy(currentTime)..add(weeks: timeOffset * 7))..startOf(Units.WEEK);
DateTime time = jiffyTime.dateTime;
```

But is that the right way to do it? Is there a more elegant way that doesn't introduce a new variable? How would one know? Tagging on `.local()`  or `.utc()` or `..local()` or `..utc()` didn't work. 

Thank you for this excellent package that makes working with DateTimes in Dart sane, and my bad if this sort of migration is documented somewhere.

**Comment by jama5262** [comment]
@willhaslett Thanks, yes, a guide should be added to the docs explaining how Jiffy uses `method cascading`. Below is what I would do in your case

If you would like to use one variable, try adding `()` around it like so

```dart
DateTime time = (
       Jiffy(Jiffy(currentTime)
       ..add(weeks: timeOffset * 7)
       ..startOf(Units.WEEK)
).dateTime;
```

You can also exclude the additional  `Jiffy` instance like so
```dart
DateTime time = (
       Jiffy(currentTime)
       ..add(weeks: timeOffset * 7)
       ..startOf(Units.WEEK)
).dateTime;
```

**_Simply do all your jiffy stuff inside the `()` and at the end call any method_** like `utc()`, `dateTime`, `format()` or the `diff()`. I will show some more examples 

Like formating
```dart
String dateFormat = (
       // Do you jiffy stuff here 👇
       Jiffy()
       ..add(hours: 20, minutes: 25)
       ..endOf(Units.DAY)
).format('MMM do yy'); // Mar 7th 21

// or

String dateFormat = (
       Jiffy([2019, 10, 19])
       ..add(weeks: 2)
       ..startOf(Units.WEEK)
).yMMMMd; // October 27, 2019
```
Like getting the difference between two dates

```dart
int diff = (
      Jiffy([2007, 1, 28])
      ..subtract(minutes: 20)
).diff([2017, 1, 29], Units.HOUR) // 4
```

And about the `utc()` and `local()` methods you can do the following options. Both of these two methods return a `DateTime` instance

```dart
DateTime  dateTimeUtc = (
       Jiffy(currentTime)
       ..add(weeks: timeOffset * 7)
       ..startOf(Units.WEEK)
      ..utc()
).dateTime;

// or 

DateTime  dateTimeUtc = (
       Jiffy(currentTime)
       ..add(weeks: timeOffset * 7)
       ..startOf(Units.WEEK)
).utc();

// same for the local

DateTime  dateTimeUtc = (
       Jiffy(currentTime)
       ..add(weeks: timeOffset * 7)
       ..startOf(Units.WEEK)
).local();
```

But I will advise on using the first option since you will still have access to `Jiffy` functionalities rather than the `DateTime` functionalities

```dart
Jiffy jiffy = (
       Jiffy(currentTime)
       ..add(weeks: timeOffset * 7)
       ..startOf(Units.WEEK)
      ..utc()
) // call all the jiffy methods like
// .format()
// .fromNow()
// .diff()

// or 

DateTime  dateTimeUtc = (
       Jiffy(currentTime)
       ..add(weeks: timeOffset * 7)
       ..startOf(Units.WEEK)
).utc(); // Here you just return `DateTime` instance and no Jiffy methods
```

@apgapg what do you think

**Comment by jama5262** [comment]
@willhaslett New version `v4.1.0` now makes it easier to use Jiffy, no need for method cascading, See below

Also check https://github.com/jama5262/jiffy/issues/59#issuecomment-610781248

```dart
DateTime time = Jiffy(currentTime).add(weeks: timeOffset * 7).startOf(Units.WEEK).dateTime;
```
