### ISSUE TITLE
 parsing short year format (ex: d.m.yy)

### ISSUE THREAD

**Issue by WahdanZ** [jama5262/jiffy#45]
**Describe the bug**
Parsing two-digit year `19` with results in `0019` and not `2019`

```
DateTime dateTimeConverter(String date) {
  return Jiffy(date, 'MM/dd/yy, HH:mm a').dateTime;
}
```
Testing
```
  test('date', () {
    expect(dateTimeConverter('3/23/19, 3:03 PM'), DateTime(2019, 3, 23, 15, 3));
  });
```
**testing fail** 
Expected: DateTime:<2019-03-23 15:03:00.000>
 Actual: DateTime:<0019-03-23 15:03:00.000>

**Comment by jama5262** [comment]
Hi @WahdanZ , thanks for the contribution. It seems that the `DateFormat` class from Intl doesn't know the full year since it was not provided in full e.g `19`. Since Jiffy runs on top of `DateFormat`, it will result the same.

It looks like we need to find a custom way, for `Jiffy` to handle this. I will work into it, or you can also contribute a `PR`

But for the meantime, you or other people who find this bug can do the following

```
DateTime dateTimeConverter(String date) {
  var newDate = 
  return Jiffy(date, 'MM/dd/yy, HH:mm a').add(years: 2000);
}
```

It does seem odd to do this, but we should find a way to fix this. **What do you think is a good way to approach this bug**?

**Comment by jama5262** [comment]
@WahdanZ Jiffy now supports the short year format

```dart
Jiffy("19", 'yy').dateTime; // 2019-01-01 00:00:00.000
Jiffy("3/23/19, 3:03 PM", 'MM/dd/yy, HH:mm a').dateTime; // 2019-03-23 15:03:00.000
```
