### ISSUE TITLE
Can't use jiffy and angular dart because of intl

### ISSUE THREAD

**Issue by jodinathan** [jama5262/jiffy#69]
isn't it possible to use intl 0.15 instead of 0.16?
so it would be possible to use it along angular dart.

**Comment by jama5262** [comment]
Hi @jodinathan , I think you actually can by using dart dependency overrides like so, just below the dependencies section in `pubspec.yaml`

```dart
dependency_overrides:
  intl: ^0.15
```

You can also check a similar Stack Overflow question [here](https://stackoverflow.com/questions/58802307/not-able-to-use-jiffy-and-flutter-localizations-because-different-versions-of-in)

Update me if it works
