### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by leszekkrol** [jama5262/jiffy#84]
Because every version of flutter_localizations from sdk depends on intl 0.17.0-nullsafety.2 and jiffy 3.0.1 depends on intl ^0.16.0, flutter_localizations from sdk is incompatible with jiffy 3.0.1.
And because no versions of jiffy match >3.0.1 <4.0.0, flutter_localizations from sdk is incompatible with jiffy ^3.0.1.
So, because fanroom depends on both jiffy ^3.0.1 and flutter_localizations any from sdk, version solving failed.

**Comment by jama5262** [comment]
Hi @leszekkrol  , have your tried dependency overrides like so, just below the dependencies section in `pubspec.yaml`

```dart
dependency_overrides:
  intl: 0.17.0-nullsafety.2
```

You can also check a similar Stack Overflow question [here](https://stackoverflow.com/questions/58802307/not-able-to-use-jiffy-and-flutter-localizations-because-different-versions-of-in)

Let me know how it turned out
