### ISSUE TITLE
startOf always returns non utc date even if date was utc

### ISSUE THREAD

**Issue by NuclleaR** [jama5262/jiffy#85]
**Describe the bug**
`Jiffy(Jiffy().utc()).dateTime.isUtc` returns true
`Jiffy(Jiffy().utc()).startOf(Units.MONTH).isUtc` returns false

**Expected behavior**
If date was in UTC, `startOf` should return UTC DateTime object

**Smartphone (please complete the following information):**
 - Device: iPhone12
 - OS: iOS14

**Comment by omidraha** [comment]
```dart
Jiffy(Jiffy().utc()).startOf(Units.DAY).dateTime.toUtc();
```

**Comment by mindfaq13** [comment]
any news on this one ?

I chose Jiffy for date-time manipulation since it promises to make tasks like date/time diff calculation easier. Dart's built-in `DateTime` only allows expressing time difference in milliseconds, seconds all the way up to days - but no months or years since these two are a bit tricky to get right.
I thought Jiffy would make for a good `DateTime` replacement, but `startOf` / `endOf` methods as of now are pretty much useless if you try to manipulate UTC timestamps, so I'm forced to look for an alternative.
Or maybe there is an obvious workaround I fail to see ?

**Comment by RobertHeim** [comment]
well I think strictly speaking UTC is not a time zone, but you need a time zone to calculate `startOf` / `endOf`. I guess most people expect that the calculation for a utc 'DateTime` should be done in time zone `GMT` and not in the local time zone.
